### PR TITLE
prolog tutorial progress

### PR DESCRIPTION
**Pull request by Eladkay**
I added a section on cuts - much of it is inspired by the old slides, the rest I wrote myself.

### CODE REVIEW

**Comment by Eladkay** [comment]
I now see that there is already a section about negation using the \+ operator. I'll merge both sections - I do think it's a better fit in the cuts section, it does the topic well to explain in what way exactly is it not logical negation but rather "cannot be proven".

**Comment by twyair** [comment]
I think it shouldn't be part of the introduction (maybe in the 3rd prolog tutorial?), so it's better to move it to a separate file.
it may be extended with slides on other control predicates (like `->/2`, see [control predicates](https://www.swi-prolog.org/pldoc/man?section=control)). do you think it'd be interesting?

**Comment by twyair** [comment]
> I now see that there is already a section about negation using the + operator. I'll merge both sections - I do think it's a better fit in the cuts section, it does the topic well to explain in what way exactly is it not logical negation but rather "cannot be proven".

the reason I put `\+` in the introduction is that it shows how prolog's reasoning is different than regular logic. that's something the students don't really understand so I think it should come early on.

**Comment by Eladkay** [comment]
> I think it shouldn't be part of the introduction (maybe in the 3rd prolog tutorial?), so it's better to move it to a separate file. it may be extended with slides on other control predicates (like `->/2`, see [control predicates](https://www.swi-prolog.org/pldoc/man?section=control)). do you think it'd be interesting?

Sure, that could work. The tutorial could be about control predicates, the main part would still be about cuts but I can write about other ones too.



> > I now see that there is already a section about negation using the + operator. I'll merge both sections - I do think it's a better fit in the cuts section, it does the topic well to explain in what way exactly is it not logical negation but rather "cannot be proven".
> 
> the reason I put `\+` in the introduction is that it shows how prolog's reasoning is different than regular logic. that's something the students don't really understand so I think it should come early on.

We can leave it there and also in the cuts section, I guess they'll just understand it more thoroughly when they get to the control predicates tutorial.

**Comment by Eladkay** [comment]
Note the new changes. I changed some things to better match the control predicates theme (in consideration of the fact that some of these things are already preliminarily mentioned in the introduction). I added sections on `repeat/1` and `->/2`. I don't think `*->/2` is interesting enough and this tutorial is too long as it is, I think.
Looking for feedback.

**Comment by twyair** [comment]
the content is great
i think there's too much text per slide that doesn't mean you should omit anything but rather split the slides vertically more often
i think you should add one more exercise (an exam question?) that uses cuts

**Pull request merged**
